@startuml add
skinparam sequenceParticipant align top

mainframe **sd** Add Command Execution

participant ":AddCommand" as AC
participant ":Expense" as expense
participant ":ExpenseService" as ES
participant ":RegularExpenseManager" as REM

AC -> expense: new Expense("lunch", 5, "food", null)
activate expense

expense --> AC: newExpense
deactivate expense

AC -> ES: addExpense(newExpense)
activate ES

ES -> REM: add(newExpense)
activate REM

REM --> ES: confirmation
deactivate REM

ES --> AC: confirmation
deactivate ES

@enduml