@startuml
'https://plantuml.com/sequence-diagram

autonumber

CommandResult -> AddCommand: execute(...)
AddCommand -[#red]> InputValidator: isNullOrBlank(...)
AddCommand <-[#red]- InputValidator: isNullOrBlank
|||
alt successful case
AddCommand -[#blue]> InputValidator: validAddFormat()
AddCommand <-[#blue]- InputValidator: input regex pattern
|||
AddCommand -> Matcher: match regex with arguments
AddCommand <-- Matcher: match groups
|||
AddCommand -> InputValidator: isValidAmountInput(...)
AddCommand <-- InputValidator: returns boolean
|||
AddCommand -> LocalDate: parses date input
group alt
LocalDate --> AddCommand: date
else parsing error
LocalDate --> AddCommand: throws DateTimeParseException
end
|||
AddCommand -> Expense: Expense()
AddCommand -> ExpenseService: adds new expense
ExpenseService -> AddCommand: confirms addition
|||
AddCommand --> CommandResult: add success
|||
else isNullOrBlank
AddCommand -[#red]-> CommandResult: invalid add format
else isInvalidAmountInput
AddCommand -[#blue]-> CommandResult: invalid amount format
else DateTimeParseException
AddCommand --> CommandResult: wrong date format
end
@enduml