@startuml
skinparam sequenceReferenceBackgroundColor #f7807c
actor "User" as user
participant ":FinTrekUi" as FT
participant ":CommandRouter" as router
participant ":CommandExecutor" as executor
participant ":CommandRegistry" as registry

participant ":<cmd>Command" as SC


user -> FT: input "/<cmd> <args>"
activate FT


FT -> router: routeUserInput("/<cmd> <args>")
activate router

router -> executor: dispatch("<cmd>", "<args>")
activate executor

executor -> registry: hasCommand("<cmd>")

alt successful case
executor -> registry: getCommand("<cmd>")
activate registry

registry --> executor
deactivate registry

executor -> SC: execute("<args>")
activate SC


ref over SC
<cmd> Command Execution
end ref

SC --> executor: CommandResult(success, message)
deactivate SC

else invalid command

registry --> executor: CommandResult(failure, message)
end


executor --> router: CommandResult(state, message)
deactivate executor

router --> FT: RouteResult(state, message)
deactivate router

FT --> user: print message
deactivate FT

@enduml