@startuml sort
skinparam sequenceReferenceBackgroundColor #white

mainframe **sd** List Sort Command Execution

participant ":ListSortCommand" as SC

SC -> Parser : parse("/list-sort")
activate Parser

Parser --> SC : ParseResult(success, ListSortParseResult(sortBy, sortDir))
deactivate Parser



participant ":ExpenseService" as ES
participant ":RegularExpenseManager" as REM
SC -> ES: getAllExpenses()
activate ES

ES -> REM: getAll()
activate REM

REM --> ES: ArrayList<>(Expenses)
deactivate REM

ES --> SC: expenses
deactivate ES


SC -> SC: getComparator(sortBy)
activate SC
SC --> SC: comparator
deactivate SC


SC -> SC: setDirection(sortDir, comparator)



SC -> SC: sort(comparator)

participant ":ExpenseReporter" as ER

SC -> ER: listExpenseBuilder(expenses)
activate ER
ER --> SC: sortedExpenses
deactivate ER



@enduml