@startuml summary
skinparam sequenceReferenceBackgroundColor #fffff

mainframe **sd**  Summary Command Execution

participant ":SummaryCommand" as SC
participant ":ExpenseReporter" as ER
participant ":RegularExpenseManager" as REM

SC -> ER: getTotalByCategory()
activate ER

ER -> REM ++ : getAll()
REM --> ER --

ER --> SC: categoryTotals

alt #LightBlue <args> is empty
SC -> ER: listAllCategoryTotal(categoryTotals)
ref over ER
List All Category Totals
end ref

else #Pink <args> is non-empty
SC -> ER: listSingleCategoryTotal(categoryTotals, <args>)

ref over ER
List Single Category Total
end ref
end

ER --> SC: formatted category summary
deactivate ER

@enduml